name = "sharex-r2-cloudflare-workers"
account_id = "<Replace with your domain>"

workers_dev = false
routes = [
	{ pattern = "<Replace with your domain>", custom_domain = true },
	# Uncomment the line below to add another domain
	#{ pattern = "<Replace with your domain>", custom_domain = true },
]

main = "src/index.ts"
compatibility_date = "2024-04-04"
compatibility_flags = ["nodejs_compat"]


[[r2_buckets]]
bucket_name = "sharex-files"
preview_bucket_name = "sharex-files"
binding = "R2_BUCKET"

[vars]
# Change to the domain your Public Bucket is connected to.
#CUSTOM_PUBLIC_BUCKET_DOMAIN = "custom-bucket.domain.tld"

# Change to not let the worker serve files, only allowing traffic through the Public Bucket. Do not set if you have old links pointing to the worker.
#ONLY_ALLOW_ACCESS_TO_PUBLIC_BUCKET = true
# Change to not allow folders in the Public Bucket.
#NO_FOLDERS = true
